image: node:latest
stages:
  - build
  - test
  - deploy
before_script:
  - npm install
build-min-code:
  stage: build
  script:
    - npm install
run-unit-test:
  stage: test
  script:
    - npm run test
# deploy-staging:
#   stage: deploy
#   script:
#     - npm run deploy-stage
#   only:
#     - develop
deploy-production:
  stage: deploy
  script:
    - docker-compose up
  only:
    - master
